version: '3.8'

services:
  ragex:
    build:
      context: .
      dockerfile: Dockerfile
    image: ragex/mcp-server:dev
    volumes:
      - .:/workspace:ro                    # Current directory (read-only)
      - ragex-data:/data                   # Persistent data
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DOCKER_CONTAINER=true
      - RAGEX_EMBEDDING_MODEL=${RAGEX_EMBEDDING_MODEL:-fast}
      - RAGEX_PERSIST_DIR=/data/chroma_db
    command: serve
    stdin_open: true
    tty: true

  # Development indexer
  indexer:
    image: ragex/mcp-server:dev
    volumes:
      - .:/workspace:ro
      - ragex-data:/data
    environment:
      - LOG_LEVEL=DEBUG
      - DOCKER_CONTAINER=true
    command: index /workspace --force
    profiles: ["index"]

volumes:
  ragex-data:
    driver: local