version: '3.8'

services:
  ragex-mcp:
    image: ragex/mcp-server:latest
    volumes:
      - ${WORKSPACE:-$PWD}:/workspace:ro
      - ragex-prod-data:/data
    environment:
      - LOG_LEVEL=WARNING
      - DOCKER_CONTAINER=true  
      - RAGEX_EMBEDDING_MODEL=${RAGEX_EMBEDDING_MODEL:-fast}
      - WORKSPACE_PATH=${WORKSPACE:-$PWD}
      - PROJECT_NAME=prod_$(echo "${WORKSPACE:-$PWD}" | sha256sum | cut -d' ' -f1 | head -c 16)
    command: serve
    stdin_open: true
    tty: true
    restart: unless-stopped
    mem_limit: 2g
    cpus: 1.0
    user: "${UID:-1000}:${GID:-1000}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=mcp-ragex"

volumes:
  ragex-prod-data:
    driver: local
    name: ragex_prod_data